canvas:
  width: 1000
  height: 300
  rowHeight: 30
dateLabelType: every_week
timeFormatLocale:
  dateTime: "%a %b %e %X %Y"
  date: "%Y/%m/%d"
  time: "%H:%M:%S"
  periods:
    - AM
    - PM
  days:
    - 日曜日
    - 月曜日
    - 火曜日
    - 水曜日
    - 木曜日
    - 金曜日
    - 土曜日
  shortDays:
    - 日
    - 月
    - 火
    - 水
    - 木
    - 金
    - 土
  months:
    - 1月
    - 2月
    - 3月
    - 4月
    - 5月
    - 6月
    - 7月
    - 8月
    - 9月
    - 10月
    - 11月
    - 12月
  shortMonths:
    - 1月
    - 2月
    - 3月
    - 4月
    - 5月
    - 6月
    - 7月
    - 8月
    - 9月
    - 10月
    - 11月
    - 12月
task:
  barHeight: 10
